### ISSUE TITLE
Wayland: Cursor position isn't centered when opening a GUI + doesn't use the system cursor

### ISSUE THREAD

**Issue by shrobbyy** [xCollateral/VulkanMod#562]
### Describe the bug

I'm using Fedora KDE on Wayland and using VulkanMod will change the cursor design to Adwaita even though I'm using the Breeze Light cursor. The more major issue is that the cursor position won't be centered if I open an inventory which is absolutely fatal for me.

### Steps to reproduce

Launch the game on Wayland.

### Log files

https://mclo.gs/93q1vnq

**Comment by IrfanKitsune** [comment]
Actually these issues aren't come from the VulkanMod itself, but it comes from the GLFW that has many problems when using GLFW as Wayland especially using custom GLFW for Vulkan support. Since these bugs between incosistent cursor position and custom cursor issue from GLFW aren't fixed yet, so the solution for fix this bug is change the session to X11 or in Prism Launcher untick "Use system installation of GLFW" for using GLFW as Xwayland instead (with the consequences numpad keys support will be minus or act only as number keys there) until these GLFW Wayland bug should be fixed.

**Comment by Anonyku05** [comment]
Kinda late but the issue of the cursor not getting to the center when opening a gui/menu still hasn't been fixed, here is a video showing it:

https://github.com/user-attachments/assets/8a1d9330-d113-49d0-b676-df2a09fafb4d

**Comment by glitchyre** [comment]
> Actually these issues aren't come from the VulkanMod itself, but it comes from the GLFW that has many problems when using GLFW as Wayland especially using custom GLFW for Vulkan support. Since these bugs between incosistent cursor position and custom cursor issue from GLFW aren't fixed yet, so the solution for fix this bug is change the session to X11 or in Prism Launcher untick "Use system installation of GLFW" for using GLFW as Xwayland instead (with the consequences numpad keys support will be minus or act only as number keys there) until these GLFW Wayland bug should be fixed.

kinda dumb question but will there be a fix to this in the future? or is it advised that we should just continue to play the game in x11?

**Comment by shrobbyy** [comment]
Quick update to this:
In snapshot 25w43a, Mojang updated LWJGL from 3.3.3 to 3.3.6 which has native Wayland support. I had created a report on [Mojira](https://mojira.dev/MC-303455) for this, which has been resolved as "fixed", but it's not actually fixed. Mojang just reverted to LWJGL 3.3.3 to run XWayland again. Mojang is waiting for LWJGL 3.4 to release which fix this Wayland issue automatically, because GLFW added the cursor warping protocol which has been added to Wayland just recently. Anyway, fixing this issue on VulkanMod might be a cake walk now.

**Comment by sstul633** [comment]
is it fixed ? im on 1.21.11 and its still a problem

**Comment by erastodib** [comment]
any updates?

**Comment by Versatile-One** [comment]
@shrobbyy Vulkanmod now runs under xwayland so these issues are fixed now. This can be closed.
